kafe 2018-11-11 00:58:45,798 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
kafe 2018-11-11 00:59:46,309 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
kafe 2018-11-13 09:06:25,904 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
kafe 2018-11-13 09:09:23,840 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
kafe 2018-11-13 09:21:44,927 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
kafe 2018-11-13 09:53:50,060 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
kafe 2018-12-29 17:44:00,832 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
kafe 2018-12-29 17:44:28,697 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
kafe 2018-12-29 17:46:53,437 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
kafe 2018-12-29 21:52:20,404 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
kafe 2018-12-29 21:55:39,565 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
matplotlib.legend 2019-01-01 14:07:21,993 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-01 14:07:41,126 :: WARNING :: No handles with labels found to put in legend.
kafe 2019-01-04 19:03:51,246 :: WARNING :: Default values not provided for any parameters of function <Inverse_square>. Setting all default parameter values to 1.0.
matplotlib.legend 2019-01-04 23:05:26,118 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-04 23:05:43,141 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-04 23:05:54,994 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-04 23:06:05,114 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-04 23:20:39,835 :: WARNING :: No handles with labels found to put in legend.
kafe 2019-01-08 08:25:47,319 :: WARNING :: More than one Fit in the same Plot detected. In this case, axis labels default to `x` and `y` and must be set explicitly if something different is desired.
matplotlib.legend 2019-01-13 17:06:17,584 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-13 17:07:10,397 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-13 17:07:36,984 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-13 17:07:58,199 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-13 17:09:15,279 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-13 17:12:23,116 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:11:39,120 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:12:31,083 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:12:51,613 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:13:05,094 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:14:30,383 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:14:39,755 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:14:44,832 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:15:52,282 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:16:11,981 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:19:23,610 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:19:41,645 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:19:49,531 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:19:55,756 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:20:51,829 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:21:01,823 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:21:26,305 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:21:40,854 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:22:27,946 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:22:45,167 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:22:55,304 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:23:38,780 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:23:49,266 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:24:00,411 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 16:24:29,249 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 19:33:29,295 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 19:34:13,170 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 19:34:43,594 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 19:34:55,989 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 19:44:47,382 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 19:45:31,411 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 19:45:56,127 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 19:47:32,563 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 19:50:08,711 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 20:36:42,229 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 20:36:42,427 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-01-14 20:36:42,638 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-10-23 16:37:21,664 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-10-23 16:37:44,339 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-10-23 16:43:29,101 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-10-23 16:43:41,391 :: WARNING :: No handles with labels found to put in legend.
matplotlib.legend 2019-10-23 16:44:35,110 :: WARNING :: No handles with labels found to put in legend.
Plotting 2019-10-29 11:03:12,081 :: INFO :: Creating selected plots...
Plotting 2019-10-29 11:03:34,705 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:03:40,592 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:04:06,323 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:04:17,400 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:04:33,528 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:05:18,454 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:35:01,822 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:35:18,097 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:35:33,210 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:35:48,454 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:35:57,470 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:36:10,371 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:36:47,063 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:37:26,872 :: INFO :: Plotting initialized
Plotting 2019-10-29 11:39:55,729 :: INFO :: Plotting initialized
Plotting 2019-10-29 13:07:19,855 :: INFO :: Plotting initialized
Plotting 2019-10-29 13:07:36,538 :: INFO :: Plotting initialized
Plotting 2019-10-29 13:07:50,256 :: INFO :: Plotting initialized
Plotting 2019-10-29 13:08:13,381 :: INFO :: Plotting initialized
Plotting 2019-10-29 13:08:53,946 :: INFO :: Plotting initialized
Plotting 2019-10-29 13:11:28,855 :: INFO :: Plotting initialized
Plotting 2019-10-29 13:11:47,288 :: INFO :: Plotting initialized
Plotting 2019-10-29 13:12:25,841 :: INFO :: Plotting initialized
Plotting 2019-10-29 13:15:39,548 :: INFO :: Plotting initialized
Plotting 2019-10-31 12:31:08,778 :: INFO :: Plotting initialized
Plotting 2019-10-31 12:44:55,233 :: INFO :: Plotting initialized
Plotting 2019-10-31 14:26:30,679 :: INFO :: Plotting initialized
Plotting 2019-10-31 15:38:04,912 :: INFO :: Plotting initialized
Root 2019-10-31 15:56:34,293 :: INFO :: Root utils initialized
Root 2019-10-31 15:57:03,567 :: INFO :: Root utils initialized
Root 2019-10-31 15:59:04,582 :: INFO :: Root utils initialized
Root 2019-10-31 16:00:10,608 :: INFO :: Root utils initialized
Root 2019-10-31 16:00:51,500 :: INFO :: Root utils initialized
Root 2019-10-31 16:01:14,477 :: INFO :: Root utils initialized
Root 2019-10-31 16:06:03,877 :: INFO :: Root utils initialized
Plotting 2019-11-28 16:08:33,851 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:16:34,416 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:18:04,255 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:18:54,364 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:19:21,051 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:19:45,040 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:19:53,665 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:20:50,998 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:20:55,298 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:21:24,378 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:22:29,369 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:23:42,067 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:28:12,697 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:28:46,627 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:29:08,709 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:35:44,912 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:39:01,757 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:55:45,212 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:58:28,295 :: INFO :: Plotting initialized
Plotting 2019-11-28 16:58:43,717 :: INFO :: Plotting initialized
Plotting 2019-11-28 20:52:58,255 :: INFO :: Plotting initialized
tornado.application 2019-11-28 20:52:59,259 :: ERROR :: Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x7f1574cd5f80>)
Traceback (most recent call last):
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 310, in advance_eventloop
    eventloop(self)
TypeError: 'NoneType' object is not callable
Plotting 2019-11-28 20:54:08,575 :: INFO :: Plotting initialized
tornado.application 2019-11-28 20:54:09,579 :: ERROR :: Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x7f98baec8560>)
Traceback (most recent call last):
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 310, in advance_eventloop
    eventloop(self)
TypeError: 'NoneType' object is not callable
Plotting 2019-11-28 20:57:08,218 :: INFO :: Plotting initialized
Plotting 2019-11-29 10:30:59,289 :: INFO :: Plotting initialized
tornado.application 2019-11-29 10:31:00,294 :: ERROR :: Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x7f4d546a59e0>)
Traceback (most recent call last):
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 310, in advance_eventloop
    eventloop(self)
TypeError: 'NoneType' object is not callable
Plotting 2019-11-29 10:31:39,680 :: INFO :: Plotting initialized
Plotting 2019-11-29 12:51:15,928 :: INFO :: Plotting initialized
Plotting 2019-11-29 12:51:22,309 :: INFO :: Plotting initialized
Plotting 2019-12-03 13:42:59,445 :: INFO :: Plotting initialized
tornado.application 2019-12-03 13:43:00,449 :: ERROR :: Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x7f1a24d3ef80>)
Traceback (most recent call last):
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 310, in advance_eventloop
    eventloop(self)
TypeError: 'NoneType' object is not callable
Plotting 2019-12-03 13:44:09,957 :: INFO :: Plotting initialized
Plotting 2019-12-03 13:44:58,549 :: INFO :: Plotting initialized
Plotting 2019-12-03 13:49:37,565 :: INFO :: Plotting initialized
Plotting 2019-12-03 13:54:07,783 :: INFO :: Plotting initialized
Plotting 2019-12-03 13:59:24,089 :: INFO :: Plotting initialized
Root 2019-12-13 20:09:09,790 :: INFO :: Root utils initialized
Plotting 2019-12-17 11:55:21,407 :: INFO :: Plotting initialized
Plotting 2019-12-17 11:57:20,688 :: INFO :: Plotting initialized
Plotting 2019-12-17 12:01:08,986 :: INFO :: Plotting initialized
Plotting 2019-12-17 12:01:16,259 :: INFO :: Plotting initialized
Plotting 2019-12-17 12:01:57,015 :: INFO :: Plotting initialized
Plotting 2019-12-17 12:02:15,015 :: INFO :: Plotting initialized
Plotting 2019-12-17 12:02:51,701 :: INFO :: Plotting initialized
Plotting 2019-12-17 12:03:16,197 :: INFO :: Plotting initialized
Plotting 2019-12-17 12:07:37,492 :: INFO :: Plotting initialized
Plotting 2019-12-17 12:12:40,487 :: INFO :: Plotting initialized
Plotting 2019-12-17 13:09:19,400 :: INFO :: Plotting initialized
Plotting 2019-12-17 13:09:33,770 :: INFO :: Plotting initialized
Plotting 2019-12-17 13:56:12,497 :: INFO :: Plotting initialized
tornado.application 2019-12-17 13:56:13,501 :: ERROR :: Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x7f65ac50ef80>)
Traceback (most recent call last):
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 310, in advance_eventloop
    eventloop(self)
TypeError: 'NoneType' object is not callable
Plotting 2019-12-17 13:56:21,445 :: INFO :: Plotting initialized
Plotting 2019-12-18 19:32:23,377 :: INFO :: Plotting initialized
Plotting 2020-01-03 12:21:06,050 :: INFO :: Plotting initialized
tornado.application 2020-01-03 12:21:07,054 :: ERROR :: Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x7fa374391f80>)
Traceback (most recent call last):
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/dcs/miniconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 310, in advance_eventloop
    eventloop(self)
TypeError: 'NoneType' object is not callable
Plotting 2020-01-03 12:28:37,101 :: INFO :: Plotting initialized
Plotting 2020-01-03 12:30:33,029 :: INFO :: Plotting initialized
Plotting 2020-01-03 12:30:33,682 :: INFO :: Plotting initialized
Plotting 2020-01-03 13:41:15,259 :: INFO :: Plotting initialized
Plotting 2020-01-03 13:42:53,339 :: INFO :: Plotting initialized
Plotting 2020-01-03 13:43:47,828 :: INFO :: Plotting initialized
Plotting 2020-01-03 13:44:37,407 :: INFO :: Plotting initialized
Plotting 2020-01-03 13:45:28,380 :: INFO :: Plotting initialized
Plotting 2020-01-03 13:46:01,565 :: INFO :: Plotting initialized
Plotting 2020-01-03 13:46:16,833 :: INFO :: Plotting initialized
Plotting 2020-01-03 13:46:29,739 :: INFO :: Plotting initialized
